---
abstract: 'state variable in perl 5.8'
author:
  - 'Jan Henning Thorsen, C<< <pm at flodhest.net> >>'
build_requires:
  Test::More: 0.5
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Var-State
no_index:
  directory:
    - inc
    - t
requires:
  Devel::Caller: 1
  Devel::LexAlias: 0.01
  PadWalker: 1
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
