---
abstract: 'Static variable in perl 5.8'
author:
  - 'Jan Henning Thorsen, C<< <pm at flodhest.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Var-State
no_index:
  directory:
    - inc
    - t
requires:
  Devel::Caller: 2.05
  Devel::LexAlias: 0.04
  PadWalker: 1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Var-State
  homepage: http://search.cpan.org/dist/Var-State
  license: http://dev.perl.org/licenses/
  repository: git://github.com//home/repositories/var-state.git
version: 0.05
