name: Var::State
version_from: lib/Var/State.pm
abstract: state [variable]; in perl 5.8 - sort-of...
author: Jan Henning Thorsen
license: perl
installdirs: site
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
requires:
    PadWalker: 0
    Devel::Caller: 0
    Devel::LexAlias: 0
build_requires:
    Test::More: 0
    Test::Pod::Coverage: 1.04
    Test::Pod: 1.14
provides:
    Var::State
        file: lib/Var/State.pm
resources:
    homepage: http://trac.flodhest.net/pm/wiki/Var-State
    repository: http://trac.flodhest.net/pm/browser/Var-State
    bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Var-State

