--- 
abstract: state [variable]; in perl 5.8 - sort-of...
author: 
  - Jan Henning Thorsen, C<< <pm at flodhest.net> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Var-State
no_index: 
  directory: 
    - inc
    - t
requires: 
  Devel::Caller: 0
  Devel::LexAlias: 0
  PadWalker: 0
version: 0.04
